name: Build Repository
on: [push]
 
jobs:
  build:
    runs-on: windows-latest
 
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: Andraste.Shared

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet Packages
      run: nuget restore Andraste.Shared/Andraste.Shared.csproj -PackagesDirectory packages
 
    - name: Build project
      run: msbuild Andraste.Shared/Andraste.Shared.csproj /p:Configuration=Release
      
    - name: Build NuGet Package
      run: nuget pack Andraste.Shared/Andraste.Shared.csproj -PackagesDirectory packages -Prop Configuration=Release
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: DLLs
        path: |
          Andraste.Shared\bin\Release\Andraste.Shared.dll
          Andraste.Shared\bin\Release\Andraste.Shared.pdb
          Andraste.Shared.0.0.0.nupkg
